# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='static/pictures/no-img.jpg', upload_to='static/pictures/'),
        ),
    ]
