# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170605_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='static/pictures/'),
        ),
    ]
