# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170605_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='model_pic',
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
